
const strapiFactory = require('@strapi/strapi').createStrapi;

async function seedJournal() {
    const strapi = await strapiFactory({ distDir: './dist' }).load();

    try {
        console.log('🌱 Seeding Journal Entries...');

        // Need some account IDs first, but we can assume we seeded them or use codes if we search
        // Helper to find Account by Code
        const findAccount = async (code) => {
            const accs = await strapi.entityService.findMany('api::chart-of-account.chart-of-account', { filters: { code } });
            return accs.length > 0 ? accs[0].id : null;
        };

        const cashId = await findAccount('1001');
        const capitalId = await findAccount('3000');
        const revenueId = await findAccount('4000');
        const expenseId = await findAccount('5001');

        if (!cashId || !capitalId) {
            console.log('⚠️ Could not find base accounts (Cash/Capital). Make sure COA is seeded.');
            return;
        }

        const entries = [
            {
                entryDate: '2026-01-01',
                reference: 'INITIAL_CAPITAL',
                description: 'Owner Investment',
                posted: true,
                details: [
                    { account: cashId, debit: 50000, credit: 0 },
                    { account: capitalId, debit: 0, credit: 50000 }
                ]
            },
            {
                entryDate: '2026-01-05',
                reference: 'INV-001',
                description: 'Fuel Sales',
                posted: true,
                details: [
                    { account: cashId, debit: 1200, credit: 0 },
                    { account: revenueId, debit: 0, credit: 1200 }
                ]
            }
        ];

        for (const entry of entries) {
            // Calculate totals
            const totalDebit = entry.details.reduce((sum, item) => sum + item.debit, 0);
            const totalCredit = entry.details.reduce((sum, item) => sum + item.credit, 0);

            await strapi.entityService.create('api::journal-entry.journal-entry', {
                data: { ...entry, totalDebit, totalCredit, isAutoGenerated: true }
            });
            console.log(`Created Entry: ${entry.reference}`);
        }

        console.log('✅ Journal Seeding complete');
    } catch (error) {
        console.error('Seeding failed', error);
    } finally {
        strapi.destroy();
    }
}

seedJournal();
